### ISSUE TITLE
hippy-vue-next-demo项目启动后页面空白

### ISSUE THREAD

**Issue by cct124** [Tencent/Hippy#3134]
启动下面的DEMO项目后
https://github.com/Tencent/Hippy/tree/master/examples/hippy-vue-next-demo

访问http://127.0.0.1:39000/
没有任何页面内容
![Snipaste_2023-04-11_15-41-07](https://user-images.githubusercontent.com/47600522/231090595-35b3aefb-09cb-421a-8dc2-d596cf21f3cb.png)

这是什么原因呢？

下面是启动输出
```shell
$ npm run web:dev

> hippy-vue-next-demo@2.0.0 web:dev
> npm run hippy:dev & node ./scripts/env-polyfill.js webpack serve --config ./scripts/hippy-webpack.web-renderer.dev.js


> hippy-vue-next-demo@2.0.0 hippy:dev
> node ./scripts/env-polyfill.js hippy-dev -c ./scripts/hippy-webpack.dev.js

Start to execute cmd: "hippy-dev -c ./scripts/hippy-webpack.dev.js"
Current openssl version: 1.1.1o+quic
Full command execute: " hippy-dev -c ./scripts/hippy-webpack.dev.js"
2023-04-11 15:45:07.658 entry info version: 0.4.15
2023-04-11 15:45:07.660 entry info start dev argv: {"_":[],"c":"./scripts/hippy-webpack.dev.js","config":"./scripts/hippy-webpack.dev.js","$0":"node_modules\\@hippy\\debug-server-next\\dist\\index-dev.js"}
* Using the @hippy/vue-css-loader defined in package.json
* Using the @vue/runtime-core defined in package.json
* Using the @hippy/vue-next defined in package.json
2023-04-11 15:45:07.893 webpack-util info webpack publicPath is set as: http://127.0.0.1:38989/
<i> [webpack-dev-server] Project is running at:
<i> [webpack-dev-server] Loopback: http://localhost:39000/, http://127.0.0.1:39000/
<i> [webpack-dev-server] Content not from webpack is served from 'D:\WebProject\Hippy\examples\hippy-vue-next-demo\public' directory
2023-04-11 15:45:10.280 entry info version: 0.4.15
2023-04-11 15:45:10.282 debug-server info start server argv: {"_":[],"port":38989,"entry":"dist/dev/index.bundle","host":"0.0.0.0","open":true,"enableIOS":true,"enable-i-o-s":true,"log":"info","iWDPPort":9000,"i-w-d-p-port":9000,"iWDPStartPort":9200,"i-w-d-p-start-port":9200,"iWDPEndPort":9300,"i-w-d-p-end-port":9300,"env":"hippy","$0":"node_modules\\@hippy\\debug-server-next\\dist\\index-debug.js"}
2023-04-11 15:45:10.327 debug-server info hippy debug steps:
1. start debug server by run 'npm run hippy:debug'
2. start dev server by run 'npm run hippy:dev'
3. open hippy pages with debugMode on mobile/emulator
4. find connected debug targets on devtools home page: http://localhost:38989/extensions/home.html?env=hippy

find full guide on https://hippyjs.org/#/guide/debug
2023-04-11 15:45:10.332 router info serve bundle: dist/dev/index.bundle; serve folder: D:\WebProject\Hippy\examples\hippy-vue-next-demo\dist\dev
2023-04-11 15:45:10.405 child-process info tunnel option: {"adb_path":"D:\\WebProject\\Hippy\\examples\\hippy-vue-next-demo\\node_modules\\@hippy\\debug-server-next\\dist\\build\\win\\adb.exe","iwdp":{"iwdp_params":["--no-frontend","--config=null:9000,:9200-9300"],"iwdp_listen_port":9000,"iwdp_path":"D:\\WebProject\\Hippy\\examples\\hippy-vue-next-demo\\node_modules\\@hippy\\debug-server-next\\dist\\build\\win\\iwdp1.8.8\\ios_webkit_debug_proxy.exe"},"only_use_iwdp":0,"iproxy_path":"D:\\WebProject\\Hippy\\examples\\hippy-vue-next-demo\\node_modules\\@hippy\\debug-server-next\\dist\\build\\win\\idevice\\iproxy.exe","idevice_info_path":"D:\\WebProject\\Hippy\\examples\\hippy-vue-next-demo\\node_modules\\@hippy\\debug-server-next\\dist\\build\\win\\idevice\\ideviceinfo.exe"}
(node:39272) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
Hash: 0335f3c8f12d6e531ef8
Version: webpack 4.46.0
Time: 4258ms
Built at: 2023/04/11 15:45:12
                               Asset      Size                   Chunks             Chunk Names
 asyncComponentFromHttp.index.bundle  28.3 KiB   asyncComponentFromHttp  [emitted]  asyncComponentFromHttp
asyncComponentFromLocal.index.bundle  28.8 KiB  asyncComponentFromLocal  [emitted]  asyncComponentFromLocal
                        index.bundle   5.4 MiB                    index  [emitted]  index
Entrypoint index = index.bundle
[1] multi ./node_modules/@hippy/vanilla-js-devtools/dist?domains=%5B%5D&host=127.0.0.1&port=38989&protocol=http @hippy/rejection-tracking-polyfill ./src/main-native.ts ./node_modules/@hippy/debug-server-next/dist/webpack-dev-server/client?protocol=ws%3A&hostname=127.0.0.1&port=38989&pathname=%2Fdebugger-proxy&role=hmr_client&hash=9f5729305b01bd0cb88597c008086894&logging=info&hot=true&liveReload=true&progress=false&overlay=false&reconnect=10 ./node_modules/@hippy/debug-server-next/dist/webpack-dev-server/client/hot/dev-server.js 76 bytes {index} [built]
[./node_modules/@hippy/debug-server-next/dist/webpack-dev-server/client/hot/dev-server.js] 1.59 KiB {index} [built]
[./node_modules/@hippy/debug-server-next/dist/webpack-dev-server/client/hot/emitter.js] 89 bytes {index} [built]
[./node_modules/@hippy/debug-server-next/dist/webpack-dev-server/client/hot/log-apply-result.js] 1.26 KiB {index} [built]
[./node_modules/@hippy/debug-server-next/dist/webpack-dev-server/client/hot/log.js] 1.25 KiB {index} [built]
[./node_modules/@hippy/debug-server-next/dist/webpack-dev-server/client/index.js?protocol=ws%3A&hostname=127.0.0.1&port=38989&pathname=%2Fdebugger-proxy&role=hmr_client&hash=9f5729305b01bd0cb88597c008086894&logging=info&hot=true&liveReload=true&progress=false&overlay=false&reconnect=10] ./node_modules/@hippy/debug-server-next/dist/webpack-dev-server/client?protocol=ws%3A&hostname=127.0.0.1&port=38989&pathname=%2Fdebugger-proxy&role=hmr_client&hash=9f5729305b01bd0cb88597c008086894&logging=info&hot=true&liveReload=true&progress=false&overlay=false&reconnect=10 4.3 KiB {index} [built]
[./node_modules/@hippy/debug-server-next/dist/webpack-dev-server/client/overlay.js] 784 bytes {index} [built]
[./node_modules/@hippy/debug-server-next/dist/webpack-dev-server/client/socket.js] 1.08 KiB {index} [built]
[./node_modules/@hippy/debug-server-next/dist/webpack-dev-server/client/utils/apply-reload.js] 156 bytes {index} [built]
[./node_modules/@hippy/debug-server-next/dist/webpack-dev-server/client/utils/createSocketURL.js] 481 bytes {index} [built]
[./node_modules/@hippy/debug-server-next/dist/webpack-dev-server/client/utils/log.js] 292 bytes {index} [built]
[./node_modules/@hippy/debug-server-next/dist/webpack-dev-server/client/utils/parseURL.js] 401 bytes {index} [built]
[./node_modules/@hippy/rejection-tracking-polyfill/index.js] 3.92 KiB {index} [built]
[./node_modules/@hippy/vanilla-js-devtools/dist/index.js?domains=%5B%5D&host=127.0.0.1&port=38989&protocol=http] ./node_modules/@hippy/vanilla-js-devtools/dist?domains=%5B%5D&host=127.0.0.1&port=38989&protocol=http 69.7 KiB {index} [built]
[./src/main-native.ts] 2.52 KiB {index} [built]
    + 282 hidden modules
<i> [webpack-dev-server] HMR websocket client is connected.
<i> [webpack-dev-server] enable HMR
<i> [webpack-dev-server] enable live reload
2023-04-11 15:45:12.762 webpack-util info bundleUrl: http://127.0.0.1:38989/index.bundle?debugUrl=ws%3A%2F%2F127.0.0.1%3A38989%2Fdebugger-proxy
2023-04-11 15:45:12.763 webpack-util info find debug page on: http://127.0.0.1:38989/extensions/home.html?hash=9f5729305b01bd0cb88597c008086894
2023-04-11 15:45:12.689 hmr-controller info HMR server connected
URIError: Failed to decode param '/%3C%=%20BASE_URL%20%%3Efavicon.ico'
    at decodeURIComponent (<anonymous>)
    at decode_param (D:\WebProject\Hippy\examples\hippy-vue-next-demo\node_modules\express\lib\router\layer.js:172:12)
    at Layer.match (D:\WebProject\Hippy\examples\hippy-vue-next-demo\node_modules\express\lib\router\layer.js:123:27)
    at matchLayer (D:\WebProject\Hippy\examples\hippy-vue-next-demo\node_modules\express\lib\router\index.js:585:18)
    at next (D:\WebProject\Hippy\examples\hippy-vue-next-demo\node_modules\express\lib\router\index.js:226:15)
    at expressInit (D:\WebProject\Hippy\examples\hippy-vue-next-demo\node_modules\express\lib\middleware\init.js:40:5)
    at Layer.handle [as handle_request] (D:\WebProject\Hippy\examples\hippy-vue-next-demo\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\WebProject\Hippy\examples\hippy-vue-next-demo\node_modules\express\lib\router\index.js:328:13)
    at D:\WebProject\Hippy\examples\hippy-vue-next-demo\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\WebProject\Hippy\examples\hippy-vue-next-demo\node_modules\express\lib\router\index.js:346:12)
    at next (D:\WebProject\Hippy\examples\hippy-vue-next-demo\node_modules\express\lib\router\index.js:280:10)
    at query (D:\WebProject\Hippy\examples\hippy-vue-next-demo\node_modules\express\lib\middleware\query.js:45:5)
    at Layer.handle [as handle_request] (D:\WebProject\Hippy\examples\hippy-vue-next-demo\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\WebProject\Hippy\examples\hippy-vue-next-demo\node_modules\express\lib\router\index.js:328:13)
    at D:\WebProject\Hippy\examples\hippy-vue-next-demo\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\WebProject\Hippy\examples\hippy-vue-next-demo\node_modules\express\lib\router\index.js:346:12)
    at next (D:\WebProject\Hippy\examples\hippy-vue-next-demo\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\WebProject\Hippy\examples\hippy-vue-next-demo\node_modules\express\lib\router\index.js:175:3)
    at Function.handle (D:\WebProject\Hippy\examples\hippy-vue-next-demo\node_modules\express\lib\application.js:181:10)
    at Server.app (D:\WebProject\Hippy\examples\hippy-vue-next-demo\node_modules\express\lib\express.js:39:9)
    at Server.emit (node:events:527:28)
    at parserOnIncoming (node:_http_server:956:12)
```

**Comment by gluefxu** [comment]
@cct124 我也遇到了这个问题，我就将 package.json 中 script 的 
`web:dev": "npm run hippy:dev & node ./scripts/env-polyfill.js ...`
改为了
`"web:dev": "node ./scripts/env-polyfill.js webpack serve ...`
其实就是将 `npm run hippy:dev & ` 给去掉了而已，就可以正常调试了。
不知道对你是否有帮助。
