### ISSUE TITLE
Error: Could not resolve './modules/StyleSheet' from packages/hippy-react-web/src/index.ts

### ISSUE THREAD

**Issue by XVilka** [Tencent/Hippy#37]
**Describe the bug**
```
> hippy@ build /home/runner/work/Hippy/Hippy
> node ./scripts/js2cpp/build.js && node ./scripts/build.js

ios convert success, output /home/runner/work/Hippy/Hippy/core/napi/jsc/native-source-code-ios.cc
android convert success, output /home/runner/work/Hippy/Hippy/core/napi/v8/native-source-code-android.cc
Circular dependency: packages/hippy-react/src/dom/document-node.ts -> packages/hippy-react/src/dom/element-node.ts -> packages/hippy-react/src/dom/view-node.ts -> packages/hippy-react/src/dom/document-node.ts
packages/hippy-react/dist/index.js 114.04kb
Error: Could not resolve './modules/StyleSheet' from packages/hippy-react-web/src/index.ts
    at error (/home/runner/work/Hippy/Hippy/node_modules/rollup/dist/rollup.js:5365:30)
    at ModuleLoader.handleMissingImports (/home/runner/work/Hippy/Hippy/node_modules/rollup/dist/rollup.js:12249:17)
    at ModuleLoader.<anonymous> (/home/runner/work/Hippy/Hippy/node_modules/rollup/dist/rollup.js:12140:30)
    at Generator.next (<anonymous>)
    at fulfilled (/home/runner/work/Hippy/Hippy/node_modules/rollup/dist/rollup.js:41:28) {
  code: 'UNRESOLVED_IMPORT',
  watchFiles: [
    '/home/runner/work/Hippy/Hippy/packages/hippy-react-web/src/index.ts',
    '/home/runner/work/Hippy/Hippy/packages/hippy-react-web/src/global.ts',
    '/home/runner/work/Hippy/Hippy/packages/hippy-react-web/src/native.ts',
    '/home/runner/work/Hippy/Hippy/packages/hippy-react-web/src/hippy.ts',
    '/home/runner/work/Hippy/Hippy/packages/hippy-react-web/src/components/view.tsx',
    '/home/runner/work/Hippy/Hippy/packages/hippy-react-web/src/components/text.tsx',
    '/home/runner/work/Hippy/Hippy/packages/hippy-react-web/src/components/image.tsx',
    '/home/runner/work/Hippy/Hippy/packages/hippy-react-web/src/components/list-view.tsx',
    '/home/runner/work/Hippy/Hippy/packages/hippy-react-web/src/components/refresh-wrapper.tsx',
```

**To Reproduce**
1. Go to https://github.com/Tencent/Hippy/pull/36/checks?check_run_id=363934987

**NOTE** - the CI job didn't fail, despite the error, you should fix your CI scripts.

**Comment by xuqingkuang** [comment]
Sorry, the case of the import file name made a mistake.

Build on the case sensitive file system will be interrupted.

Fixed in #46
