### ISSUE TITLE
hippy-vue-next-demo项目启动报错

### ISSUE THREAD

**Issue by ChitogeYX** [Tencent/Hippy#3735]
启动下面的DEMO项目后
https://github.com/Tencent/Hippy/tree/master/examples/hippy-vue-next-demo

这是什么原因呢？

下面是启动输出

```
npm run web:dev

> hippy-vue-next-demo@2.0.0 web:dev
> npm run hippy:dev & node ./scripts/env-polyfill.js webpack serve --config ./scripts/hippy-webpack.web-renderer.dev.js


> hippy-vue-next-demo@2.0.0 hippy:dev
> node ./scripts/env-polyfill.js hippy-dev -c ./scripts/hippy-webpack.dev.js

Start to execute cmd: "hippy-dev -c ./scripts/hippy-webpack.dev.js"
Current openssl version: 1.1.1t+quic
Full command execute: " hippy-dev -c ./scripts/hippy-webpack.dev.js"
2024-01-23 15:39:19.204 entry info version: 0.5.0
2024-01-23 15:39:19.206 entry info start dev argv: {"_":[],"c":"./scripts/hippy-webpack.dev.js","config":"./scripts/hippy-webpack.dev.js","$0":"node_modules\\@hippy\\debug-server-next\\dist\\index-dev.js"}
* Using the @hippy/vue-css-loader defined in package.json
* Using the @vue/runtime-core defined in package.json
* Using the @hippy/vue-next defined in package.json
2024-01-23 15:39:19.530 webpack-util info webpack publicPath is set as: http://127.0.0.1:38989/
<i> [webpack-dev-server] Project is running at:
<i> [webpack-dev-server] Loopback: http://localhost:39000/, http://127.0.0.1:39000/
<i> [webpack-dev-server] Content not from webpack is served from 'C:\Users\78118\Desktop\hippy-vue-next-demo\public' directory
2024-01-23 15:39:24.932 entry info version: 0.5.0
2024-01-23 15:39:24.936 debug-server info start server argv: {"_":[],"port":38989,"entry":"dist/dev/index.bundle","host":"0.0.0.0","open":true,"enableIOS":true,"enable-i-o-s":true,"log":"info","iWDPPort":9000,"i-w-d-p-port":9000,"iWDPStartPort":9200,"i-w-d-p-start-port":9200,"iWDPEndPort":9300,"i-w-d-p-end-port":9300,"env":"hippy","$0":"node_modules\\@hippy\\debug-server-next\\dist\\index-debug.js"}
(node:22436) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
2024-01-23 15:39:25.348 process-handler error unhandledRejection Error: The specified module could not be found.
\\?\C:\Users\78118\Desktop\hippy-vue-next-demo\node_modules\@hippy\debug-server-next\dist\build\win\Tunnel.node
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1275:18)
    at Module.load (node:internal/modules/cjs/loader:1069:32)
    at Function.Module._load (node:internal/modules/cjs/loader:904:12)
    at Module.require (node:internal/modules/cjs/loader:1093:19)
    at require (node:internal/modules/cjs/helpers:108:18)
    at Object.<anonymous> (C:\Users\78118\Desktop\hippy-vue-next-demo\node_modules\@hippy\debug-server-next\dist\child-process\import-addon-win.js:23:47)
    at Module._compile (node:internal/modules/cjs/loader:1191:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1245:10)
    at Module.load (node:internal/modules/cjs/loader:1069:32)
    at Function.Module._load (node:internal/modules/cjs/loader:904:12)
    at Module.require (node:internal/modules/cjs/loader:1093:19)
    at require (node:internal/modules/cjs/helpers:108:18)
    at C:\Users\78118\Desktop\hippy-vue-next-demo\node_modules\@hippy\debug-server-next\dist\child-process\import-addon.js:37:66
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
2024-01-23 15:39:26.628 process-handler info on exit: ["exit"]
Hash: e07c24a7f95754abd7f6
Version: webpack 4.47.0
Time: 6529ms
Built at: 2024/01/23 15:39:27
                               Asset      Size                   Chunks             Chunk Names
 asyncComponentFromHttp.index.bundle  28.1 KiB   asyncComponentFromHttp  [emitted]  asyncComponentFromHttp
asyncComponentFromLocal.index.bundle  28.6 KiB  asyncComponentFromLocal  [emitted]  asyncComponentFromLocal
                        index.bundle  5.57 MiB                    index  [emitted]  index
Entrypoint index = index.bundle
[1] multi ./node_modules/@hippy/vanilla-js-devtools/dist?domains=%5B%5D&host=127.0.0.1&port=38989&protocol=http @hippy/rejection-tracking-polyfill ./src/main-native.ts ./node_modules/@hippy/debug-server-next/dist/webpack-dev-server/client?protocol=ws%3A&hostname=127.0.0.1&port=38989&pathname=%2Fdebugger-proxy&role=hmr_client&hash=d9127aaf28de014a5b76866de2b88914&logging=info&hot=true&liveReload=true&progress=false&overlay=false&reconnect=10 ./node_modules/@hippy/debug-server-next/dist/webpack-dev-server/client/hot/dev-server.js 76 bytes {index} [built]
[./node_modules/@hippy/debug-server-next/dist/webpack-dev-server/client/hot/dev-server.js] 1.59 KiB {index} [built]
[./node_modules/@hippy/debug-server-next/dist/webpack-dev-server/client/hot/emitter.js] 89 bytes {index} [built]
[./node_modules/@hippy/debug-server-next/dist/webpack-dev-server/client/hot/log-apply-result.js] 1.26 KiB {index} [built]
[./node_modules/@hippy/debug-server-next/dist/webpack-dev-server/client/hot/log.js] 1.25 KiB {index} [built]
[./node_modules/@hippy/debug-server-next/dist/webpack-dev-server/client/index.js?protocol=ws%3A&hostname=127.0.0.1&port=38989&pathname=%2Fdebugger-proxy&role=hmr_client&hash=d9127aaf28de014a5b76866de2b88914&logging=info&hot=true&liveReload=true&progress=false&overlay=false&reconnect=10] ./node_modules/@hippy/debug-server-next/dist/webpack-dev-server/client?protocol=ws%3A&hostname=127.0.0.1&port=38989&pathname=%2Fdebugger-proxy&role=hmr_client&hash=d9127aaf28de014a5b76866de2b88914&logging=info&hot=true&liveReload=true&progress=false&overlay=false&reconnect=10 4.3 KiB {index} [built]
[./node_modules/@hippy/debug-server-next/dist/webpack-dev-server/client/overlay.js] 784 bytes {index} [built]
[./node_modules/@hippy/debug-server-next/dist/webpack-dev-server/client/socket.js] 1.08 KiB {index} [built]
[./node_modules/@hippy/debug-server-next/dist/webpack-dev-server/client/utils/apply-reload.js] 156 bytes {index} [built]
[./node_modules/@hippy/debug-server-next/dist/webpack-dev-server/client/utils/createSocketURL.js] 481 bytes {index} [built]
[./node_modules/@hippy/debug-server-next/dist/webpack-dev-server/client/utils/log.js] 292 bytes {index} [built]
[./node_modules/@hippy/debug-server-next/dist/webpack-dev-server/client/utils/parseURL.js] 401 bytes {index} [built]
[./node_modules/@hippy/rejection-tracking-polyfill/index.js] 3.92 KiB {index} [built]
[./node_modules/@hippy/vanilla-js-devtools/dist/index.js?domains=%5B%5D&host=127.0.0.1&port=38989&protocol=http] ./node_modules/@hippy/vanilla-js-devtools/dist?domains=%5B%5D&host=127.0.0.1&port=38989&protocol=http 69.7 KiB {index} [built]
[./src/main-native.ts] 1.8 KiB {index} [built]
    + 299 hidden modules
<w> [webpack-dev-server] HMR websocket error:  Error: connect ECONNREFUSED 127.0.0.1:38989
<w>     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16) {
<w>   errno: -4078,
<w>   code: 'ECONNREFUSED',
<w>   syscall: 'connect',
<w>   address: '127.0.0.1',
<w>   port: 38989
<w> }
<w> [webpack-dev-server] Hippy use @hippy/debug-server-next to transit HMR message, connect to debug server failed, recommend to run `npm run hippy:debug` first!
<w> [webpack-dev-server] HMR websocket is closed(1006), will try to reconnect when you modify source code.
<i> [webpack-dev-server] enable HMR
<i> [webpack-dev-server] enable live reload
2024-01-23 15:39:27.146 webpack-util info bundleUrl: http://127.0.0.1:38989/index.bundle?debugUrl=ws%3A%2F%2F127.0.0.1%3A38989%2Fdebugger-proxy
2024-01-23 15:39:27.147 webpack-util info find debug page on: http://127.0.0.1:38989/extensions/home.html?hash=d9127aaf28de014a5b76866de2b88914
<w> [webpack-dev-server] HMR websocket error:  Error: connect ECONNREFUSED 127.0.0.1:38989
<w>     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16) {
<w>   errno: -4078,
<w>   code: 'ECONNREFUSED',
<w>   syscall: 'connect',
<w>   address: '127.0.0.1',
<w>   port: 38989
<w> }
<w> [webpack-dev-server] Hippy use @hippy/debug-server-next to transit HMR message, connect to debug server failed, recommend to run `npm run hippy:debug` first!
<w> [webpack-dev-server] HMR websocket is closed(1006), will try to reconnect when you modify source code.
```

**Comment by KongQingzhi** [comment]
我也遇到了这个问题，请问解决了吗？
