### ISSUE TITLE
测试Demo添加新页面时编译失败

### ISSUE THREAD

**Issue by yuyehen** [Tencent/Hippy#3955]
**Describe the bug**
(base) ➜  hippy-react-demo git:(main) ✗ npm run hippy:build
﻿
> hippy-react-demo@2.0.0 hippy:build
> node ./scripts/env-polyfill.js webpack --config ./scripts/hippy-webpack.ios.js --config ./scripts/hippy-webpack.android.js
﻿
Start to execute cmd: "webpack --config ./scripts/hippy-webpack.ios.js --config ./scripts/hippy-webpack.android.js"
Current openssl version: 3.0.13+quic
Full command execute: "cross-env-os NODE_OPTIONS=--openssl-legacy-provider webpack --config ./scripts/hippy-webpack.ios.js --config ./scripts/hippy-webpack.android.js"
* Using the @hippy/react defined in package.json
* Using the @hippy/react defined in package.json
[webpack-cli] ModuleNotFoundError: Module not found: Error: Can't resolve './messageHomePage' in '/Users/sunwei/Documents/Hippy/driver/js/examples/hippy-react-demo/src/pages'
at /Users/sunwei/Documents/Hippy/driver/js/examples/hippy-react-demo/node_modules/webpack/lib/Compilation.js:925:10
at /Users/sunwei/Documents/Hippy/driver/js/examples/hippy-react-demo/node_modules/webpack/lib/NormalModuleFactory.js:401:22
at /Users/sunwei/Documents/Hippy/driver/js/examples/hippy-react-demo/node_modules/webpack/lib/NormalModuleFactory.js:130:21
at /Users/sunwei/Documents/Hippy/driver/js/examples/hippy-react-demo/node_modules/webpack/lib/NormalModuleFactory.js:224:22
at /Users/sunwei/Documents/Hippy/driver/js/examples/hippy-react-demo/node_modules/neo-async/async.js:2830:7
at /Users/sunwei/Documents/Hippy/driver/js/examples/hippy-react-demo/node_modules/neo-async/async.js:6877:13
at /Users/sunwei/Documents/Hippy/driver/js/examples/hippy-react-demo/node_modules/webpack/lib/NormalModuleFactory.js:214:25
at /Users/sunwei/Documents/Hippy/driver/js/examples/hippy-react-demo/node_modules/enhanced-resolve/lib/Resolver.js:213:14
at /Users/sunwei/Documents/Hippy/driver/js/examples/hippy-react-demo/node_modules/enhanced-resolve/lib/Resolver.js:285:5
at eval (eval at create (/Users/sunwei/Documents/Hippy/driver/js/examples/hippy-react-demo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
at /Users/sunwei/Documents/Hippy/driver/js/examples/hippy-react-demo/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:44:7
at /Users/sunwei/Documents/Hippy/driver/js/examples/hippy-react-demo/node_modules/enhanced-resolve/lib/Resolver.js:285:5
at eval (eval at create (/Users/sunwei/Documents/Hippy/driver/js/examples/hippy-react-demo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
at /Users/sunwei/Documents/Hippy/driver/js/examples/hippy-react-demo/node_modules/enhanced-resolve/lib/Resolver.js:285:5
at eval (eval at create (/Users/sunwei/Documents/Hippy/driver/js/examples/hippy-react-demo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
at /Users/sunwei/Documents/Hippy/driver/js/examples/hippy-react-demo/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43
at /Users/sunwei/Documents/Hippy/driver/js/examples/hippy-react-demo/node_modules/enhanced-resolve/lib/Resolver.js:285:5
at eval (eval at create (/Users/sunwei/Documents/Hippy/driver/js/examples/hippy-react-demo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
at /Users/sunwei/Documents/Hippy/driver/js/examples/hippy-react-demo/node_modules/enhanced-resolve/lib/RootPlugin.js:37:38
at _next42 (eval at create (/Users/sunwei/Documents/Hippy/driver/js/examples/hippy-react-demo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:8:1)
at eval (eval at create (/Users/sunwei/Documents/Hippy/driver/js/examples/hippy-react-demo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:31:1)
at /Users/sunwei/Documents/Hippy/driver/js/examples/hippy-react-demo/node_modules/enhanced-resolve/lib/Resolver.js:285:5
at eval (eval at create (/Users/sunwei/Documents/Hippy/driver/js/examples/hippy-react-demo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
at /Users/sunwei/Documents/Hippy/driver/js/examples/hippy-react-demo/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43
at /Users/sunwei/Documents/Hippy/driver/js/examples/hippy-react-demo/node_modules/enhanced-resolve/lib/Resolver.js:285:5
at eval (eval at create (/Users/sunwei/Documents/Hippy/driver/js/examples/hippy-react-demo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
at /Users/sunwei/Documents/Hippy/driver/js/examples/hippy-react-demo/node_modules/enhanced-resolve/lib/Resolver.js:285:5
at eval (eval at create (/Users/sunwei/Documents/Hippy/driver/js/examples/hippy-react-demo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
at /Users/sunwei/Documents/Hippy/driver/js/examples/hippy-react-demo/node_modules/enhanced-resolve/lib/DirectoryExistsPlugin.js:27:15
at /Users/sunwei/Documents/Hippy/driver/js/examples/hippy-react-demo/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:85:15
at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
resolve './messageHomePage' in '/Users/sunwei/Documents/Hippy/driver/js/examples/hippy-react-demo/src/pages'
using description file: /Users/sunwei/Documents/Hippy/driver/js/examples/hippy-react-demo/package.json (relative path: ./src/pages)
Field 'browser' doesn't contain a valid alias configuration
using description file: /Users/sunwei/Documents/Hippy/driver/js/examples/hippy-react-demo/package.json (relative path: ./src/pages/messageHomePage)
no extension
Field 'browser' doesn't contain a valid alias configuration
/Users/sunwei/Documents/Hippy/driver/js/examples/hippy-react-demo/src/pages/messageHomePage doesn't exist
.js
Field 'browser' doesn't contain a valid alias configuration
/Users/sunwei/Documents/Hippy/driver/js/examples/hippy-react-demo/src/pages/messageHomePage.js doesn't exist
.jsx
Field 'browser' doesn't contain a valid alias configuration
/Users/sunwei/Documents/Hippy/driver/js/examples/hippy-react-demo/src/pages/messageHomePage.jsx doesn't exist
.json
Field 'browser' doesn't contain a valid alias configuration
/Users/sunwei/Documents/Hippy/driver/js/examples/hippy-react-demo/src/pages/messageHomePage.json doesn't exist
as directory
/Users/sunwei/Documents/Hippy/driver/js/examples/hippy-react-demo/src/pages/messageHomePage doesn't exist
❌ Execute cmd - "cross-env-os NODE_OPTIONS=--openssl-legacy-provider webpack --config ./scripts/hippy-webpack.ios.js --config ./scripts/hippy-webpack.android.js" error: * Using the @hippy/react defined in package.json
﻿
﻿
﻿
- Hippy native SDK version: [e.g. 3.x]
﻿

**Comment by yuyehen** [comment]
添加的文件是tsxx类型的
