### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by lionvoom** [Tencent/Hippy#4068]
```
mac@macdeMBP-2 js % npm run init

> init
> npm install && npx lerna bootstrap && npm run build


up to date, audited 2098 packages in 3s

200 packages are looking for funding
  run `npm fund` for details

24 vulnerabilities (9 moderate, 14 high, 1 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
lerna notice cli v6.1.0
lerna info Bootstrapping 11 packages
lerna info Installing external dependencies
lerna info Symlinking packages and binaries
lerna success Bootstrapped 11 packages

> build
> node ./scripts/build.js

/Users/mac/Downloads/Hippy/driver/js/node_modules/ttypescript/lib/loadTypescript.js:13
        function __() { this.constructor = d; }
                                         ^

TypeError: Cannot set property constructor of [object Object] which has only a getter
    at new __ (/Users/mac/Downloads/Hippy/driver/js/node_modules/ttypescript/lib/loadTypescript.js:13:42)
    at __extends (/Users/mac/Downloads/Hippy/driver/js/node_modules/ttypescript/lib/loadTypescript.js:14:84)
    at /Users/mac/Downloads/Hippy/driver/js/node_modules/ttypescript/lib/loadTypescript.js:65:5
    at Object.<anonymous> (/Users/mac/Downloads/Hippy/driver/js/node_modules/ttypescript/lib/loadTypescript.js:100:2)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at require (node:internal/modules/helpers:179:18)

Node.js v20.16.0
```

**Comment by unfixa1** [comment]
Make sure you are using the latest version of ttypescript, or a version compatible with Node.js v20.16.0:
npm install ttypescript@latest
If it still doesn't work, you need to lower the nodejs version to 18.x.
In addition, you can use [Servbay](servbay.com) to deploy your development environment, which supports one-click switching of node.js versions,
and ensures that there are no compatibility conflicts in the environment.
