### ISSUE TITLE
vue demo -> npm run hippy:build  报错

### ISSUE THREAD

**Issue by chihong2012** [Tencent/Hippy#79]
sbt-dev-2:hippy-vue-demo sbt$ npm run hippy:build

> hippy-vue-demo@2.0.0 hippy:build /Users/sbt/Desktop/Hippy/examples/hippy-vue-demo
> webpack --config ./scripts/hippy-webpack.ios.js --config ./scripts/hippy-webpack.android.js

ModuleNotFoundError: Module not found: Error: Can't resolve 'vue' in '/Users/sbt/Desktop/Hippy/examples/hippy-vue-demo/src'
    at factory.create (/Users/sbt/Desktop/Hippy/examples/hippy-vue-demo/node_modules/webpack/lib/Compilation.js:925:10)
    at factory (/Users/sbt/Desktop/Hippy/examples/hippy-vue-demo/node_modules/webpack/lib/NormalModuleFactory.js:401:22)
    at resolver (/Users/sbt/Desktop/Hippy/examples/hippy-vue-demo/node_modules/webpack/lib/NormalModuleFactory.js:130:21)
    at asyncLib.parallel (/Users/sbt/Desktop/Hippy/examples/hippy-vue-demo/node_modules/webpack/lib/NormalModuleFactory.js:224:22)
    at /Users/sbt/Desktop/Hippy/examples/hippy-vue-demo/node_modules/neo-async/async.js:2830:7
    at /Users/sbt/Desktop/Hippy/examples/hippy-vue-demo/node_modules/neo-async/async.js:6877:13
    at normalResolver.resolve (/Users/sbt/Desktop/Hippy/examples/hippy-vue-demo/node_modules/webpack/lib/NormalModuleFactory.js:214:25)
    at doResolve (/Users/sbt/Desktop/Hippy/examples/hippy-vue-demo/node_modules/enhanced-resolve/lib/Resolver.js:213:14)
    at hook.callAsync (/Users/sbt/Desktop/Hippy/examples/hippy-vue-demo/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
    at _fn0 (eval at create (/Users/sbt/Desktop/Hippy/examples/hippy-vue-demo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at resolver.doResolve (/Users/sbt/Desktop/Hippy/examples/hippy-vue-demo/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:44:7)
    at hook.callAsync (/Users/sbt/Desktop/Hippy/examples/hippy-vue-demo/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
    at _fn0 (eval at create (/Users/sbt/Desktop/Hippy/examples/hippy-vue-demo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at hook.callAsync (/Users/sbt/Desktop/Hippy/examples/hippy-vue-demo/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
    at _fn0 (eval at create (/Users/sbt/Desktop/Hippy/examples/hippy-vue-demo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at resolver.doResolve (/Users/sbt/Desktop/Hippy/examples/hippy-vue-demo/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43)
    at hook.callAsync (/Users/sbt/Desktop/Hippy/examples/hippy-vue-demo/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
    at _fn0 (eval at create (/Users/sbt/Desktop/Hippy/examples/hippy-vue-demo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:657:1)
    at resolver.doResolve (/Users/sbt/Desktop/Hippy/examples/hippy-vue-demo/node_modules/enhanced-resolve/lib/AliasPlugin.js:67:43)
    at hook.callAsync (/Users/sbt/Desktop/Hippy/examples/hippy-vue-demo/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
    at _fn0 (eval at create (/Users/sbt/Desktop/Hippy/examples/hippy-vue-demo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at resolver.doResolve (/Users/sbt/Desktop/Hippy/examples/hippy-vue-demo/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:44:7)
    at hook.callAsync (/Users/sbt/Desktop/Hippy/examples/hippy-vue-demo/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
    at _fn0 (eval at create (/Users/sbt/Desktop/Hippy/examples/hippy-vue-demo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at hook.callAsync (/Users/sbt/Desktop/Hippy/examples/hippy-vue-demo/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
    at _fn0 (eval at create (/Users/sbt/Desktop/Hippy/examples/hippy-vue-demo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at resolver.doResolve (/Users/sbt/Desktop/Hippy/examples/hippy-vue-demo/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43)
    at hook.callAsync (/Users/sbt/Desktop/Hippy/examples/hippy-vue-demo/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
    at _fn43 (eval at create (/Users/sbt/Desktop/Hippy/examples/hippy-vue-demo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at hook.callAsync (/Users/sbt/Desktop/Hippy/examples/hippy-vue-demo/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
    at _fn0 (eval at create (/Users/sbt/Desktop/Hippy/examples/hippy-vue-demo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at resolver.doResolve (/Users/sbt/Desktop/Hippy/examples/hippy-vue-demo/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43)
    at hook.callAsync (/Users/sbt/Desktop/Hippy/examples/hippy-vue-demo/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
    at _fn1 (eval at create (/Users/sbt/Desktop/Hippy/examples/hippy-vue-demo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at hook.callAsync (/Users/sbt/Desktop/Hippy/examples/hippy-vue-demo/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
    at _fn0 (eval at create (/Users/sbt/Desktop/Hippy/examples/hippy-vue-demo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
resolve 'vue' in '/Users/sbt/Desktop/Hippy/examples/hippy-vue-demo/src'
  Parsed request is a module
  using description file: /Users/sbt/Desktop/Hippy/examples/hippy-vue-demo/package.json (relative path: ./src)
    aliased with mapping 'vue': '/Users/sbt/Desktop/Hippy/packages/hippy-vue' to '/Users/sbt/Desktop/Hippy/packages/hippy-vue'
      using description file: /Users/sbt/Desktop/Hippy/examples/hippy-vue-demo/package.json (relative path: ./src)
        Field 'browser' doesn't contain a valid alias configuration
        using description file: /Users/sbt/Desktop/Hippy/packages/hippy-vue/package.json (relative path: .)
          no extension
            Field 'browser' doesn't contain a valid alias configuration
            /Users/sbt/Desktop/Hippy/packages/hippy-vue is not a file
          .js
            Field 'browser' doesn't contain a valid alias configuration
            /Users/sbt/Desktop/Hippy/packages/hippy-vue.js doesn't exist
          .vue
            Field 'browser' doesn't contain a valid alias configuration
            /Users/sbt/Desktop/Hippy/packages/hippy-vue.vue doesn't exist
          .json
            Field 'browser' doesn't contain a valid alias configuration
            /Users/sbt/Desktop/Hippy/packages/hippy-vue.json doesn't exist
          as directory
            existing directory
              use ./dist/index.js from main in package.json
                using description file: /Users/sbt/Desktop/Hippy/packages/hippy-vue/package.json (relative path: .)
                  Field 'browser' doesn't contain a valid alias configuration
                  using description file: /Users/sbt/Desktop/Hippy/packages/hippy-vue/package.json (relative path: ./dist/index.js)
                    no extension
                      Field 'browser' doesn't contain a valid alias configuration
                      /Users/sbt/Desktop/Hippy/packages/hippy-vue/dist/index.js doesn't exist
                    .js
                      Field 'browser' doesn't contain a valid alias configuration
                      /Users/sbt/Desktop/Hippy/packages/hippy-vue/dist/index.js.js doesn't exist
                    .vue
                      Field 'browser' doesn't contain a valid alias configuration
                      /Users/sbt/Desktop/Hippy/packages/hippy-vue/dist/index.js.vue doesn't exist
                    .json
                      Field 'browser' doesn't contain a valid alias configuration
                      /Users/sbt/Desktop/Hippy/packages/hippy-vue/dist/index.js.json doesn't exist
                    as directory
                      /Users/sbt/Desktop/Hippy/packages/hippy-vue/dist/index.js doesn't exist
              using path: /Users/sbt/Desktop/Hippy/packages/hippy-vue/index
                using description file: /Users/sbt/Desktop/Hippy/packages/hippy-vue/package.json (relative path: ./index)
                  no extension
                    Field 'browser' doesn't contain a valid alias configuration
                    /Users/sbt/Desktop/Hippy/packages/hippy-vue/index doesn't exist
                  .js
                    Field 'browser' doesn't contain a valid alias configuration
                    /Users/sbt/Desktop/Hippy/packages/hippy-vue/index.js doesn't exist
                  .vue
                    Field 'browser' doesn't contain a valid alias configuration
                    /Users/sbt/Desktop/Hippy/packages/hippy-vue/index.vue doesn't exist
                  .json
                    Field 'browser' doesn't contain a valid alias configuration
                    /Users/sbt/Desktop/Hippy/packages/hippy-vue/index.json doesn't exist
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hippy-vue-demo@2.0.0 hippy:build: `webpack --config ./scripts/hippy-webpack.ios.js --config ./scripts/hippy-webpack.android.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hippy-vue-demo@2.0.0 hippy:build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sbt/.npm/_logs/2020-01-01T03_02_18_508Z-debug.log

**Comment by jeromehan** [comment]
> sbt-dev-2:hippy-vue-demo sbt$ npm run hippy:build
> 
> > hippy-vue-demo@2.0.0 hippy:build /Users/sbt/Desktop/Hippy/examples/hippy-vue-demo
> > webpack --config ./scripts/hippy-webpack.ios.js --config ./scripts/hippy-webpack.android.js
> 
> ModuleNotFoundError: Module not found: Error: Can't resolve 'vue' in '/Users/sbt/Desktop/Hippy/examples/hippy-vue-demo/src'
> at factory.create (/Users/sbt/Desktop/Hippy/examples/hippy-vue-demo/node_modules/webpack/lib/Compilation.js:925:10)
> at factory (/Users/sbt/Desktop/Hippy/examples/hippy-vue-demo/node_modules/webpack/lib/NormalModuleFactory.js:401:22)
> at resolver (/Users/sbt/Desktop/Hippy/examples/hippy-vue-demo/node_modules/webpack/lib/NormalModuleFactory.js:130:21)
> at asyncLib.parallel (/Users/sbt/Desktop/Hippy/examples/hippy-vue-demo/node_modules/webpack/lib/NormalModuleFactory.js:224:22)
> at /Users/sbt/Desktop/Hippy/examples/hippy-vue-demo/node_modules/neo-async/async.js:2830:7
> at /Users/sbt/Desktop/Hippy/examples/hippy-vue-demo/node_modules/neo-async/async.js:6877:13
> at normalResolver.resolve (/Users/sbt/Desktop/Hippy/examples/hippy-vue-demo/node_modules/webpack/lib/NormalModuleFactory.js:214:25)
> at doResolve (/Users/sbt/Desktop/Hippy/examples/hippy-vue-demo/node_modules/enhanced-resolve/lib/Resolver.js:213:14)
> at hook.callAsync (/Users/sbt/Desktop/Hippy/examples/hippy-vue-demo/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
> at _fn0 (eval at create (/Users/sbt/Desktop/Hippy/examples/hippy-vue-demo/node_modules/tapable/lib/HookCodeFactory.js:33:10), :15:1)
> at resolver.doResolve (/Users/sbt/Desktop/Hippy/examples/hippy-vue-demo/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:44:7)
> at hook.callAsync (/Users/sbt/Desktop/Hippy/examples/hippy-vue-demo/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
> at _fn0 (eval at create (/Users/sbt/Desktop/Hippy/examples/hippy-vue-demo/node_modules/tapable/lib/HookCodeFactory.js:33:10), :15:1)
> at hook.callAsync (/Users/sbt/Desktop/Hippy/examples/hippy-vue-demo/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
> at _fn0 (eval at create (/Users/sbt/Desktop/Hippy/examples/hippy-vue-demo/node_modules/tapable/lib/HookCodeFactory.js:33:10), :27:1)
> at resolver.doResolve (/Users/sbt/Desktop/Hippy/examples/hippy-vue-demo/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43)
> at hook.callAsync (/Users/sbt/Desktop/Hippy/examples/hippy-vue-demo/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
> at _fn0 (eval at create (/Users/sbt/Desktop/Hippy/examples/hippy-vue-demo/node_modules/tapable/lib/HookCodeFactory.js:33:10), :657:1)
> at resolver.doResolve (/Users/sbt/Desktop/Hippy/examples/hippy-vue-demo/node_modules/enhanced-resolve/lib/AliasPlugin.js:67:43)
> at hook.callAsync (/Users/sbt/Desktop/Hippy/examples/hippy-vue-demo/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
> at _fn0 (eval at create (/Users/sbt/Desktop/Hippy/examples/hippy-vue-demo/node_modules/tapable/lib/HookCodeFactory.js:33:10), :15:1)
> at resolver.doResolve (/Users/sbt/Desktop/Hippy/examples/hippy-vue-demo/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:44:7)
> at hook.callAsync (/Users/sbt/Desktop/Hippy/examples/hippy-vue-demo/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
> at _fn0 (eval at create (/Users/sbt/Desktop/Hippy/examples/hippy-vue-demo/node_modules/tapable/lib/HookCodeFactory.js:33:10), :15:1)
> at hook.callAsync (/Users/sbt/Desktop/Hippy/examples/hippy-vue-demo/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
> at _fn0 (eval at create (/Users/sbt/Desktop/Hippy/examples/hippy-vue-demo/node_modules/tapable/lib/HookCodeFactory.js:33:10), :27:1)
> at resolver.doResolve (/Users/sbt/Desktop/Hippy/examples/hippy-vue-demo/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43)
> at hook.callAsync (/Users/sbt/Desktop/Hippy/examples/hippy-vue-demo/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
> at _fn43 (eval at create (/Users/sbt/Desktop/Hippy/examples/hippy-vue-demo/node_modules/tapable/lib/HookCodeFactory.js:33:10), :16:1)
> at hook.callAsync (/Users/sbt/Desktop/Hippy/examples/hippy-vue-demo/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
> at _fn0 (eval at create (/Users/sbt/Desktop/Hippy/examples/hippy-vue-demo/node_modules/tapable/lib/HookCodeFactory.js:33:10), :27:1)
> at resolver.doResolve (/Users/sbt/Desktop/Hippy/examples/hippy-vue-demo/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43)
> at hook.callAsync (/Users/sbt/Desktop/Hippy/examples/hippy-vue-demo/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
> at _fn1 (eval at create (/Users/sbt/Desktop/Hippy/examples/hippy-vue-demo/node_modules/tapable/lib/HookCodeFactory.js:33:10), :16:1)
> at hook.callAsync (/Users/sbt/Desktop/Hippy/examples/hippy-vue-demo/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
> at _fn0 (eval at create (/Users/sbt/Desktop/Hippy/examples/hippy-vue-demo/node_modules/tapable/lib/HookCodeFactory.js:33:10), :15:1)
> resolve 'vue' in '/Users/sbt/Desktop/Hippy/examples/hippy-vue-demo/src'
> Parsed request is a module
> using description file: /Users/sbt/Desktop/Hippy/examples/hippy-vue-demo/package.json (relative path: ./src)
> aliased with mapping 'vue': '/Users/sbt/Desktop/Hippy/packages/hippy-vue' to '/Users/sbt/Desktop/Hippy/packages/hippy-vue'
> using description file: /Users/sbt/Desktop/Hippy/examples/hippy-vue-demo/package.json (relative path: ./src)
> Field 'browser' doesn't contain a valid alias configuration
> using description file: /Users/sbt/Desktop/Hippy/packages/hippy-vue/package.json (relative path: .)
> no extension
> Field 'browser' doesn't contain a valid alias configuration
> /Users/sbt/Desktop/Hippy/packages/hippy-vue is not a file
> .js
> Field 'browser' doesn't contain a valid alias configuration
> /Users/sbt/Desktop/Hippy/packages/hippy-vue.js doesn't exist
> .vue
> Field 'browser' doesn't contain a valid alias configuration
> /Users/sbt/Desktop/Hippy/packages/hippy-vue.vue doesn't exist
> .json
> Field 'browser' doesn't contain a valid alias configuration
> /Users/sbt/Desktop/Hippy/packages/hippy-vue.json doesn't exist
> as directory
> existing directory
> use ./dist/index.js from main in package.json
> using description file: /Users/sbt/Desktop/Hippy/packages/hippy-vue/package.json (relative path: .)
> Field 'browser' doesn't contain a valid alias configuration
> using description file: /Users/sbt/Desktop/Hippy/packages/hippy-vue/package.json (relative path: ./dist/index.js)
> no extension
> Field 'browser' doesn't contain a valid alias configuration
> /Users/sbt/Desktop/Hippy/packages/hippy-vue/dist/index.js doesn't exist
> .js
> Field 'browser' doesn't contain a valid alias configuration
> /Users/sbt/Desktop/Hippy/packages/hippy-vue/dist/index.js.js doesn't exist
> .vue
> Field 'browser' doesn't contain a valid alias configuration
> /Users/sbt/Desktop/Hippy/packages/hippy-vue/dist/index.js.vue doesn't exist
> .json
> Field 'browser' doesn't contain a valid alias configuration
> /Users/sbt/Desktop/Hippy/packages/hippy-vue/dist/index.js.json doesn't exist
> as directory
> /Users/sbt/Desktop/Hippy/packages/hippy-vue/dist/index.js doesn't exist
> using path: /Users/sbt/Desktop/Hippy/packages/hippy-vue/index
> using description file: /Users/sbt/Desktop/Hippy/packages/hippy-vue/package.json (relative path: ./index)
> no extension
> Field 'browser' doesn't contain a valid alias configuration
> /Users/sbt/Desktop/Hippy/packages/hippy-vue/index doesn't exist
> .js
> Field 'browser' doesn't contain a valid alias configuration
> /Users/sbt/Desktop/Hippy/packages/hippy-vue/index.js doesn't exist
> .vue
> Field 'browser' doesn't contain a valid alias configuration
> /Users/sbt/Desktop/Hippy/packages/hippy-vue/index.vue doesn't exist
> .json
> Field 'browser' doesn't contain a valid alias configuration
> /Users/sbt/Desktop/Hippy/packages/hippy-vue/index.json doesn't exist
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! hippy-vue-demo@2.0.0 hippy:build: `webpack --config ./scripts/hippy-webpack.ios.js --config ./scripts/hippy-webpack.android.js`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the hippy-vue-demo@2.0.0 hippy:build script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR! /Users/sbt/.npm/_logs/2020-01-01T03_02_18_508Z-debug.log

![image](https://user-images.githubusercontent.com/19773879/71638223-2de5b700-2c95-11ea-9a95-ac5bed39a4f3.png)
scripts下的所有  alias 全部替换成node_modules路径。某些情况下，alias确实找不到，写成../node_modules就能正确找到了。

**Comment by xuqingkuang** [comment]
alias 只是为了保持用到最新的 sdk，方便测试一些未发布的新特性，在 Hippy 目录下运行 `npm run build` 编译一下 sdk 就行了。

实在不行把 alias 删了也行啊，何必重定向。
